FROM ubuntu:latest

LABEL maintainer "user"

ENV USER user
ENV HOME /home/${USER}
ENV SHELL /bin/bash

RUN useradd -m ${USER}
RUN gpasswd -a ${USER} sudo
RUN echo "${USER}:work" | chpasswd
SHELL ["/bin/bash", "-c"]

RUN apt-get update && apt-get install -y
RUN apt-get install -y git sudo curl gcc make mysql

RUN curl -O https://dl.google.com/go/go1.17.1.linux-amd64.tar.gz
RUN rm -rf /usr/local/go && tar -C /usr/local -xzf go1.17.1.linux-amd64.tar.gz
ENV PATH $PATH:/usr/local/go/bin
ENV PATH $PATH:${HOME}/go/bin
RUN go version

RUN curl -sL https://deb.nodesource.com/setup_16.x | bash -
RUN apt install -y nodejs
RUN npm install npm@latest -g

COPY . .

WORKDIR /home/${USER}/flontend
RUN npm install

WORKDIR /home/${USER}

CMD ["make", "run"]